//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CxDev.rc
//
#define IDC_BACK                        3
#define IDC_UP                          3
#define IDC_DOWN                        4
#define IDR_CXDEVTYPE_CNTR_IP           6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING101                   101
#define IDP_FAILED_TO_CREATE            102
#define IDP_OLE_INIT_FAILED2            103
#define IDD_CUSTZOOM                    106
#define IDB_TOOLBOX                     110
#define ID_TOOLBOX                      111
#define ID_EXPLORER_BAR                 114
#define ID_LAYER_1                      115
#define ID_LAYER_2                      116
#define ID_LAYER_3                      117
#define ID_LAYER_4                      118
#define ID_LAYER_5                      119
#define ID_LAYER_6                      120
#define ID_LAYER_7                      121
#define ID_LAYER_8                      122
#define ID_LAYER_9                      123
#define ID_LAYER_10                     124
#define ID_LAYER_11                     125
#define ID_LAYER_12                     126
#define ID_LAYER_13                     127
#define ID_LAYER_14                     128
#define ID_LAYER_15                     129
#define ID_LAYER_16                     130
#define IDC_FONTNAME                    131
#define IDC_FONTSIZE                    132
#define ID_EXPLORER_WND                 132
#define ID_VIEW_FORMATBAR               133
#define ID_SYMBOL_WND                   133
#define ID_CHAR_BOLD                    134
#define ID_MODULE_WND                   134
#define ID_PROPERTY_BAR                 135
#define ID_BOXCTRL_WND                  135
#define ID_CHAR_ITALIC                  136
#define ID_CHAR_UNDERLINE               137
#define ID_CHAR_COLOR                   138
#define IDR_MAINFRAME                   139
#define IDC_TEXTCOLOR                   140
#define IDR_CXDEVTYPE                   141
#define IDR_LAYOUTFRAME                 142
#define IDR_TOOLBAR1                    143
#define IDR_SCRIPTFRAME                 144
#define IDR_LAYOUTBAR                   145
#define IDI_PROJECT                     146
#define IDI_PICTURES                    147
#define IDI_PICTURE                     148
#define IDB_FORMATBAR                   149
#define IDR_TOOLBAR5                    150
#define IDD_SAVEPROMPT                  151
#define IDB_CURSOR                      152
#define IDB_BITMAP_PATTERN1             153
#define IDB_BITMAP_PATTERN              154
#define IDI_FORM                        155
#define IDR_MENU_TRACK                  156
#define IDI_MAINFORM                    157
#define IDD_INSERTCONTROL               158
#define IDC_PAUSE                       159
#define IDD_PAGE_APP                    160
#define IDD_PAGE_GEN                    160
#define IDD_PAGE_MAINFORM               161
#define IDD_PAGE_SUBFORM                162
#define IDD_PAGE_OBJECT                 163
#define IDB_EXPLORER_ICONS              164
#define IDI_FOLDER_CLOSE                165
#define IDI_FOLDER_OPEN                 166
#define IDB_GLIB_LARGE                  167
#define IDB_GLIB_SMALL                  168
#define IDB_GLIB_TOOL                   169
#define IDR_SYMBOLWND                   170
#define IDB_SYMBOL_LARGE                171
#define IDR_FULLSCREEN                  172
#define IDB_SYMBOL_SMALL                173
#define IDB_FONTTYPE                    174
#define IDB_SPLASH                      175
#define IDB_LAYER_STATE                 176
#define IDD_GROUP_DESIGN                177
#define IDD_EXPROP_ITEM                 178
#define IDD_SYMBOL_PROP                 178
#define IDR_MENU_LAYOUTINPLACE          179
#define IDD_LAYER                       179
#define IDB_LSTATE                      180
#define IDR_MODULEWND                   180
#define IDR_REPORTFRAME                 181
#define IDI_CODEMODULE                  182
#define IDB_HANDLE_ROTATE               183
#define IDI_SUBFORM                     183
#define IDB_HANDLE_GENERAL              184
#define IDC_ROTATE                      184
#define IDD_OPC_DATASOURCE              187
#define IDD_OPC_SERVER                  188
#define IDD_DIALOG1                     191
#define IDI_REPORT                      194
#define IDI_SUBREPORT                   195
#define IDD_REPORT_WIZARD               195
#define IDD_REPORT_FIELD                196
#define IDB_COLUMNAR                    197
#define IDB_TABULAR                     199
#define IDI_PORTRAIT                    199
#define ID_DRAW_SELECT                  200
#define IDB_JUSTIFIED                   200
#define IDI_LANDSCAPE                   200
#define IDD_FILE_NEW                    200
#define ID_DRAW_LINE                    201
#define ID_DRAW_RECT                    202
#define ID_DRAW_ROUNDRECT               203
#define ID_DRAW_ELLIPSE                 204
#define ID_DRAW_POLYLINE                205
#define ID_DRAW_PIPE                    206
#define ID_DRAW_POLYGON                 207
#define ID_DRAW_ARC                     208
#define ID_DRAW_PIE                     209
#define ID_DRAW_CHORD                   210
#define ID_DRAW_TEXT                    211
#define ID_DRAW_DATALINK                212
#define ID_DRAW_VARIABLE                213
#define ID_DRAW_BUTTON                  214
#define ID_DRAW_MENU                    215
#define ID_DRAW_TIMER                   216
#define ID_DRAW_CHART                   217
#define ID_DRAW_ALMSUM                  218
#define IDS_HOMEPAGEADDR                219
#define IDS_DEFAULT_FONTCOLOR           220
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_LIST                        1001
#define IDC_CHECK3                      1001
#define IDCANCEL2                       1002
#define IDC_EDIT3                       1002
#define IDC_EDIT_WIDTH                  1003
#define IDC_EDIT4                       1003
#define IDC_EDIT_HEIGHT                 1004
#define IDC_CHECK_GRID                  1005
#define IDC_EDIT6                       1005
#define IDC_BACKGROUND                  1006
#define IDC_FOREGROUND                  1007
#define IDC_GRIDCOLOR                   1008
#define IDC_TREE_PROP                   1008
#define IDC_INSERT_LINE                 1009
#define IDC_DELLINE                     1011
#define IDC_EDITLINE                    1012
#define IDC_STATIC_PREVIEW              1015
#define IDC_GROUP_TAG                   1016
#define IDC_EDIT_NAME                   1017
#define IDC_COMBO_TYPE                  1018
#define IDC_EDIT_DES                    1019
#define IDC_EDIT_VALID                  1020
#define IDC_CHECK_ALL                   1024
#define IDC_BUTTON_ADVANCE              1025
#define IDC_PREVIEW                     1026
#define IDC_EDIT_MODDIR                 1027
#define IDC_EDIT_SYMDIR                 1028
#define IDC_EDIT_WORKDIR                1029
#define IDC_EDIT_FOLDER                 1029
#define IDC_FOLDER                      1029
#define IDC_EDIT_DEFAULT                1030
#define IDC_PICTURE                     1030
#define IDC_BUTTON1                     1032
#define IDC_BT_VISIBLE                  1032
#define IDC_HIGHLIGHTFILLCOLOR          1032
#define IDC_BUTTON_FOLDER               1032
#define IDC_ADD_SERVER                  1032
#define IDC_RIGHT_ONE                   1032
#define IDC_LIST2                       1033
#define IDC_BUTTON_DEFAULT              1033
#define IDC_BUTTON4                     1033
#define IDC_EDIT_SERVER                 1033
#define IDC_RIGHT_ALL                   1033
#define IDC_BUTTON_PICTURE              1033
#define IDC_STATIC_LAYERGROUP           1034
#define IDC_BUTTON2                     1034
#define IDC_BUTTON5                     1034
#define IDC_REMOVE_SERVER               1034
#define IDC_LEFT_ONE                    1034
#define IDC_BUTTON3                     1035
#define IDC_LEFT_ALL                    1035
#define IDC_BT_LOCK                     1038
#define IDC_BT_HIDDEN                   1039
#define IDC_BT_UNLOCK                   1040
#define IDC_GROUPTAG_LIST               1041
#define IDC_FILLCOLOR                   1042
#define IDC_HIGHLIGHTEDGECOLOR          1043
#define IDC_EDGECOLOR                   1044
#define IDC_COMBO1                      1045
#define IDC_BUTTON_VALEXP               1047
#define IDC_VALUE                       1049
#define IDC_BUTTON_ENUM                 1050
#define IDC_CONTROLS                    1053
#define IDC_CHECK1                      1054
#define IDC_CHECK2                      1054
#define IDC_LIST1                       1055
#define IDC_IMPLEMENTEDCATEGORIES       1056
#define IDC_WWW                         1056
#define IDC_RIGHT                       1056
#define IDC_REQUIREDCATEGORIES          1057
#define IDC_PROP_VALUE                  1057
#define IDC_IGNOREREQUIREDCATEGORIES    1058
#define IDC_TREE1                       1059
#define IDC_PROPERTYCTRL1               1060
#define IDC_TREE2                       1061
#define IDC_GRID_COLOR                  1066
#define IDC_GRID_ENABLE                 1067
#define IDC_GRID_SPACE_WIDTH            1068
#define IDC_GRID_SPACE_HEIGHT           1069
#define IDC_ALIGN_GRID                  1070
#define IDC_NEXT                        1070
#define IDC_FINISH                      1071
#define IDC_RECT                        1072
#define IDC_LEFT                        1073
#define IDC_COLUMNAR                    1075
#define IDC_TABULAR                     1076
#define IDC_JUSTIFIED                   1077
#define IDC_PORTRAIT                    1078
#define IDC_LANDSCAPE                   1079
#define IDC_LAYOUT                      1080
#define IDC_ORIENTATION                 1081
#define IDC_SERVERPATH                  1083
#define IDC_CHECK31                     1087
#define IDC_USESETTING                  1087
#define IDC_APP_NAME                    1090
#define IDD_FOLDERNAME                  27532
#define IDD_GRID_SETTING                27533
#define IDD_REPORT_LAYOUT               27534
#define IDD_TAB_ORDER                   27535
#define IDC_HANDCUR                     27537
#define ID_CANCEL_EDIT                  32768
#define ID_VIEW_PROPERTY_BAR            32771
#define ID_VIEW_EXPLORER_BAR            32772
#define ID_VIEW_ZOOM50                  32779
#define ID_VIEW_ZOOM75                  32780
#define ID_VIEW_ZOOM100                 32781
#define ID_VIEW_ZOOM150                 32782
#define ID_VIEW_ZOOM200                 32783
#define ID_VIEW_ZOOM400                 32784
#define ID_VIEW_ZOOMCUSTOM              32785
#define ID_ALIGN_BOTTOM                 32786
#define ID_ALIGN_HORIZ_CENTER           32787
#define ID_ALIGN_LEFT                   32788
#define ID_ALIGN_VERT_CENTER            32789
#define ID_ALIGN_RIGHT                  32790
#define ID_ALIGN_TOP                    32791
#define ID_UNGROUP_OBJECT               32793
#define ID_ITEM_MOVEFORWARD             32794
#define ID_ITEM_MOVEBACK                32795
#define ID_SPACE_EVENVERT               32797
#define ID_SPACE_EVENHORIZ              32798
#define ID_VIEW_FULL_SCREEN             32799
#define ID_EDIT_SELECTALL               32801
#define ID_VIEW_OBJECT                  32802
#define ID_VIEW_SCRIPT                  32803
#define ID_INSERT_LIBGRF                32804
#define ID_INSERT_CONTROL               32805
#define ID_EDIT_PROPERTIES              32807
#define ID_GROUP_OBJECT                 32808
#define ID_INSERT_BITMAP                32813
#define ID_BUTTON32815                  32815
#define ID_ADD_FORM                     32818
#define ID_ADD_REPORT                   32819
#define ID_ADD_CODE                     32820
#define ID_TRACK_MOVE                   32821
#define ID_TRACK_COPY                   32822
#define ID_FILE_IMPORT                  32823
#define ID_FILE_SAVE_ALL                32824
#define ID_FILE_SAVE_PICTURE            32825
#define ID_PICTURE_SETUP                32826
#define ID_TOBE_CHILD                   32844
#define ID_TOBE_CHILDMODULE             32845
#define ID_TOBE_MAIN                    32846
#define ID_OBJECT_PROPERTY              32847
#define ID_EDIT_CONVERTTOBMP            32849
#define ID_ADDTO_MODULE                 32850
#define ID_ADDTO_SYMBOL                 32851
#define ID_VIEW_APPEAR_EXPERT           32852
#define ID_LAYER_SETUP                  32855
#define ID_VIEW_TOOLBOX                 32867
#define ID_ARRAGE_SAMEHIGHT             32869
#define ID_ARRAGE_SAMEWIDTH             32870
#define ID_ARRAGE_BOTH                  32871
#define ID_ITEM_FORWARD                 32872
#define ID_ITEM_BACKWORD                32873
#define ID_ITEM_FORWARD_MOST            32874
#define ID_ITEM_BACKWORD_MOST           32875
#define ID_VIEW_NORMAL                  32876
#define ID_VIEW_SPACE                   32877
#define ID_VIEW_STATUS                  32878
#define ID_HELP_CONTENT                 32879
#define ID_HELP_SEARCH                  32880
#define ID_EDIT_SCRIPT                  32882
#define ID_TRACKER_RESIZE               32884
#define ID_TRACKER_RESHAPE              32885
#define ID_TRACKER_ROTATE               32886
#define ID_OBJECT_FORWARD_MOST          32887
#define ID_OBJECT_BACKWORD_MOST         32888
#define ID_OBJECT_MOVEFORWARD           32889
#define ID_OBJECT_MOVEBACK              32890
#define ID_EDIT_CLONE                   32891
#define ID_FILE_SAVE_PICTURE_AS         32895
#define ID_FILE_EXPORT                  32896
#define ID_EDIT_PROPERTY                32897
#define ID_LIB_PROPERTY                 32897
#define ID_BUTTON32901                  32901
#define ID_BUTTON32902                  32902
#define ID_BUTTON32903                  32903
#define ID_BUTTON32904                  32904
#define ID_BUTTON32905                  32905
#define ID_BUTTON32906                  32906
#define ID_BUTTON32907                  32907
#define ID_BUTTON32908                  32908
#define ID_BUTTON32909                  32909
#define ID_BUTTON32910                  32910
#define ID_BUTTON32911                  32911
#define ID_BUTTON32912                  32912
#define ID_BUTTON32913                  32913
#define ID_BUTTON32914                  32914
#define ID_NONE                         32915
#define ID_CREATE_SYMBOL                32918
#define ID_DESIGN_SYMBOL                32919
#define ID_PICTURE_RUN                  32920
#define ID_VIEW_LAYOUT_BAR              32921
#define ID_VIEW_STAND_BAR               32922
#define ID_LIB_RENAME                   32924
#define ID_LIB_NEW                      32925
#define ID_LIB_OPEN                     32926
#define ID_LIB_DELETE                   32927
#define ID_ADD_SUBMODULE                32929
#define ID_PICTURE_OPTIONS              32930
#define ID_PICTURE_OPCSERVER            32931
#define ID_ADD_CONTROL                  32934
#define ID_DESIGN_SUBFORM               32935
#define ID_EDIT_SUBFORM                 32936
#define ID_CREATE_SUBFORM               32937
#define ID_BREAK_SYMBOL                 32938
#define ID_BREAK_SUBFORM                32939
#define ID_BUTTON32945                  32945
#define ID_EDIT_GOTO                    32946
#define ID_BOOKMARK_TOGGLE              32948
#define ID_BOOKMART_NEXT                32949
#define ID_BOOKMART_PREVIOUS            32950
#define ID_BOOKMARK_CLEAR               32951
#define ID_BOOKMARK_NEXT                32952
#define ID_BOOKMARK_PREVIOUS            32953
#define ID_GRID_SETTING                 32954
#define ID_ADD_SUBREPORT                32955
#define ID_PAGE_SETUP                   32956
#define ID_VIEW_ACTION_EXPERT           32958
#define ID_VIEW_DYNAMIC_EXPERT          32959
#define ID_EXECUTE_APPMC                32965
#define ID_BUTTON32967                  32967
#define ID_INSERT_RUNCTRL               32969
#define ID_BUTTON32971                  32971
#define ID_BUTTON32972                  32972
#define ID_ADD_BLANK_REPORT             32973
#define ID_ADD_REPORT_WIZARD            32974
#define ID_ROTATE_LEFT                  32975
#define ID_ROTATE_RIGHT                 32976
#define ID_MIRROR_HORIZ                 32977
#define ID_MIRROR_VERT                  32978
#define ID_HORIZ_CENTER                 32979
#define ID_VERT_CENTER                  32980
#define ID_WINDOW_CLOSE                 32981
#define ID_WINDOW_CLOSEALL              32982
#define ID_WINDOW_NEXT                  32983
#define ID_WINDOW_PREVIOUS              32984
#define ID_TAB_ORDER                    32985
#define IDS_INVALID_NUMBER              57346
#define IDS_INVALID_FONTSIZE            57347
#define IDS_TITLE_FORMATBAR             57348
#define IDS_APROPNAME_FONT              57349
#define IDS_DEFAULT_EDGECOLOR           57608
#define IDS_DEFAULT_FILLCOLOR           57610
#define IDS_NEW_PICTURE                 57611
#define IDS_CANNOT_OPEN_PICTURE         57612
#define IDS_CANNOT_CREATE_PICTURE       57613
#define IDS_SERVERNOTFOUND              57614
#define IDS_CREATEFAILED                57615
#define IDS_APROPNAME_USERMODE          57645
#define IDS_DEFAULT_FILLSTYLE           57645
#define IDS_DEFAULT_BACKGROUNDCOLOR     57646
#define IDC_COMBOBOX_VAR                60000
#define IDC_COMBOBOX_EVENT              60001
#define IDC_LISTBOX_AUTOCOM             60200
#define IDC_FOLDERNAME                  60301
#define ID_ADD_FOLDER                   60305
#define ID_REMOVE_FOLDER                60306
#define ID_RENAME_FOLDER                60307
#define ID_ADD_ITEM                     60308
#define ID_REMOVE_ITEM                  60309
#define IDS_MAINFORM                    61446
#define ID_APPEAR_EXPERT                61447
#define ID_DYNAMIC_EXPERT               61448
#define ID_EVENT_EXPERT                 61449
#define IDS_BAD_INSTALL                 61450
#define ID_INDICATOR_CURSOR             61451
#define IDS_ADDOBJ                      61452
#define IDS_SINGLESELECTION             61453
#define IDS_MULTIPLESELECTION           61454

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32986
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           178
#endif
#endif
