//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CxRunCtrl.rc
//
#define IDS_RUNCTRL                     1
#define IDB_RUNCTRL                     1
#define IDS_RUNCTRL_PPG                 2
#define ID_BREAK                        3
#define IDC_KEY_F1                      108
#define IDC_KEY_F2                      109
#define IDC_KEY_F3                      110
#define IDC_KEY_F4                      111
#define IDC_KEY_F5                      112
#define IDC_KEY_F6                      113
#define IDC_KEY_F7                      114
#define IDC_KEY_F8                      115
#define IDC_KEY_F9                      116
#define IDC_KEY_F10                     117
#define IDC_KEY_F11                     118
#define IDC_KEY_F12                     119
#define IDC_KEY_INS                     120
#define IDC_KEY_DEL                     121
#define IDC_KEY_WAVE                    122
#define IDC_KEY_1                       123
#define IDC_KEY_2                       124
#define IDC_KEY_3                       125
#define IDC_KEY_4                       126
#define IDC_KEY_6                       127
#define IDC_KEY_7                       128
#define IDR_CXRUNTYPE                   129
#define IDC_KEY_8                       129
#define IDR_PRINT                       130
#define IDC_KEY_9                       130
#define IDD_KEYBOARD                    130
#define IDC_KEY_0                       131
#define IDC_KEY_MINUS                   134
#define IDC_KEY_PLUS                    135
#define IDS_RUNCTRL_PPG_CAPTION         200
#define IDD_PROPPAGE_RUNCTRL            200
#define IDC_INFO                        201
#define IDD_SCRIPT_ERROR                201
#define IDC_USER_NAME                   201
#define ID_IGNORE                       202
#define IDI_TOOLTIP                     202
#define IDC_PASSWORD                    202
#define ID_IGNORE_ALL                   203
#define IDC_DESC                        203
#define IDD_USER_ITEM                   203
#define IDC_PASSWORD2                   203
#define IDC_HAND1                       203
#define IDC_EDIT1                       204
#define IDC_PASSWORD3                   204
#define IDC_HAND2                       204
#define IDC_EDIT2                       205
#define IDC_SELECT_ALL                  206
#define IDB_SMALLICONS                  206
#define IDC_SELECT_NONE                 207
#define IDC_CHECK3                      208
#define IDC_CHECK4                      209
#define IDC_BUTTON1                     210
#define IDC_RADIO1                      211
#define IDC_DELETE_USER                 211
#define IDC_PRIVILEGE                   211
#define IDC_RADIO2                      212
#define IDC_MODIFY_USER                 212
#define IDD_PREVIEW_TOOLBAR             213
#define ID_PREVIEW_PAGE                 213
#define IDC_AREA                        213
#define IDD_USER_MANAGER                214
#define IDD_LOGIN                       215
#define IDC_ADD_USER                    215
#define IDC_GROUP                       215
#define IDD_CHANGE_PASSWORD             216
#define IDC_USERS                       217
#define IDD_KEYBOARD_NUMBER             217
#define IDC_KEY_ESC                     1020
#define IDC_KEY_BACK                    1032
#define IDC_KEY_PAGEUP                  1033
#define IDC_KEY_TAB                     1034
#define IDC_KEY_PAUSE                   1035
#define IDC_KEY_SEPARATOR               1047
#define IDC_KEY_PAGEDOWN                1048
#define IDC_KEY_CAPS                    1049
#define IDC_KEY_ENTER                   1062
#define IDC_KEY_HOME                    1063
#define IDC_KEY_SHIFT                   1064
#define IDC_KEY_END                     1078
#define IDC_KEY_CONTROL                 1079
#define IDC_KEY_WIN                     1080
#define IDC_KEY_MENU                    1081
#define IDC_KEY_SPACE                   1082
#define IDC_KEY_APP                     1083
#define IDC_KEY_LEFT                    1091
#define IDC_KEY_DOWN                    1092
#define IDC_KEY_RIGHT                   1093
#define IDC_KEY_Q                       1094
#define IDC_KEY_W                       1095
#define IDC_KEY_E                       1096
#define IDC_KEY_R                       1097
#define IDC_KEY_T                       1098
#define IDC_KEY_Y                       1099
#define IDC_KEY_U                       1100
#define IDC_KEY_I                       1101
#define IDC_KEY_O                       1102
#define IDC_KEY_P                       1103
#define IDC_KEY_BRA                     1104
#define IDC_KEY_KET                     1105
#define IDC_KEY_A                       1106
#define IDC_KEY_S                       1107
#define IDC_KEY_D                       1108
#define IDC_KEY_F                       1109
#define IDC_KEY_G                       1110
#define IDC_KEY_H                       1111
#define IDC_KEY_J                       1112
#define IDC_KEY_K                       1113
#define IDC_KEY_L                       1114
#define IDC_KEY_COLON                   1115
#define IDC_KEY_QUOTE                   1116
#define IDC_KEY_Z                       1117
#define IDC_KEY_X                       1118
#define IDC_KEY_C                       1119
#define IDC_KEY_V                       1120
#define IDC_KEY_B                       1121
#define IDC_KEY_N                       1122
#define IDC_KEY_M                       1123
#define IDC_KEY_COMMA                   1124
#define IDC_KEY_PERIOD                  1125
#define IDC_KEY_SLASH                   1126
#define IDC_KEY_UP                      1128
#define IDC_KEY_5                       1216
#define ID_VIEW_FULL_SCREEN             32771
#define IDS_SCRIPTERRORFORMAT           57605

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         219
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
