//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CxDrawShapes.rc
//
#define IDS_PROJNAME                    100
#define IDR_DRAWLINE                    101
#define IDR_DRAWRECTANGLE               102
#define IDR_DRAWELLIPSE                 103
#define IDR_DRAWROUNDRECTANGLE          104
#define IDR_DRAWPOLYLINE                105
#define IDR_DRAWPIPE                    106
#define IDD_CXBUTTONGENPAGE             106
#define IDR_DRAWPOLYGON                 107
#define IDR_DRAWARC                     108
#define IDD_CXPIPEGENPAGE               108
#define IDR_DRAWPIE                     109
#define IDR_DRAWCHORD                   110
#define IDR_DRAWTXT                     111
#define IDR_DRAWDATALINK                112
#define IDR_DRAWBUTTON                  113
#define IDR_DRAWIMAGE                   114
#define IDR_FLOATPOINT                  115
#define IDS_TITLECxButtonGenPage        120
#define IDS_TITLECxShapeGenPage         121
#define IDD_CXSHAPEGENPAGE              122
#define IDS_HELPFILECxShapeGenPage      122
#define IDC_HORFILLPER                  122
#define IDS_DOCSTRINGCxShapeGenPage     123
#define IDC_VERFILLPER                  123
#define IDR_CXSHAPEGENPAGE              124
#define IDC_EDGEWIDTH                   124
#define IDS_TITLECxPipeGenPage          125
#define IDS_HELPFILECxPipeGenPage       126
#define IDS_DOCSTRINGCxPipeGenPage      127
#define IDR_CXPIPEGENPAGE               128
#define IDS_HELPFILECxButtonGenPage     129
#define IDS_DOCSTRINGCxButtonGenPage    130
#define IDR_CXBUTTONGENPAGE             131
#define IDS_TITLECxImageGenPage         133
#define IDS_HELPFILECxImageGenPage      134
#define IDS_DOCSTRINGCxImageGenPage     135
#define IDR_CXIMAGEGENPAGE              136
#define IDD_CXIMAGEGENPAGE              138
#define IDS_TITLECxTextGenPage          139
#define IDD_CXTEXTGENPAGE               139
#define IDS_HELPFILECxTextGenPage       140
#define IDS_DOCSTRINGCxTextGenPage      141
#define IDR_CXTEXTGENPAGE               142
#define IDS_TITLECxTextTextPage         144
#define IDS_HELPFILECxTextTextPage      145
#define IDS_DOCSTRINGCxTextTextPage     146
#define IDR_CXTEXTTEXTPAGE              147
#define IDS_TITLECxDataLinkGenPage      149
#define IDS_HELPFILECxDataLinkGenPage   150
#define IDS_DOCSTRINGCxDataLinkGenPage  151
#define IDR_CXDATALINKGENPAGE           152
#define IDR_DRAWVARIABLE                154
#define IDS_TITLECxVariableGenPage      155
#define IDS_HELPFILECxVariableGenPage   156
#define IDS_DOCSTRINGCxVariableGenPage  157
#define IDR_CXVARIABLEGENPAGE           158
#define IDR_DRAWTIMER                   160
#define IDS_TITLECxTimerGenPage         161
#define IDS_HELPFILECxTimerGenPage      162
#define IDS_DOCSTRINGCxTimerGenPage     163
#define IDR_CXTIMERGENPAGE              164
#define IDD_CXTIMERGENPAGE              165
#define IDR_DRAWMENU                    166
#define IDS_TITLECxMenuGenPage          167
#define IDS_HELPFILECxMenuGenPage       168
#define IDS_DOCSTRINGCxMenuGenPage      169
#define IDR_CXMENUGENPAGE               170
#define IDD_CXMENUGENPAGE               171
#define IDB_ARROW                       201
#define IDC_RADIUS                      201
#define IDC_FONT                        201
#define IDC_FONT_NAME                   201
#define IDC_LIGHT_COLOR                 202
#define IDC_FORECOLOR                   202
#define IDC_COMBO_INDEX                 202
#define IDB_TRUETYPE                    202
#define IDD_CXTEXTTEXTPAGE              202
#define IDC_FLOW                        203
#define IDC_BACKCOLOR                   203
#define IDC_BUTTON_ADD                  203
#define IDC_FONT_STYLE                  203
#define IDD_CXDATALINKGENPAGE           203
#define IDC_CAPTION                     204
#define IDC_BUTTON_DELETE               204
#define IDC_FONT_SIZE                   204
#define IDC_CREATE_EXPRESSION           204
#define IDD_CXVARIABLEGENPAGE           204
#define IDC_LIQUID_COLOR                205
#define IDC_NORMAL                      205
#define IDC_STRIKE_THROUGH              205
#define IDB_MENU                        205
#define IDI_UP                          205
#define IDC_FLOW_SPEED                  206
#define IDC_CLEARNORMAL                 206
#define IDC_UNDER_LINE                  206
#define IDI_DOWN                        206
#define IDC_FLOW_DIRECTION              207
#define IDC_STATIC_OUT                  207
#define IDC_FONT_COLOR                  207
#define IDI_RIGHT                       207
#define IDC_DARK_COLOR                  208
#define IDC_CLEARHOVER                  208
#define IDC_SAMPLE_BOX                  208
#define IDI_LEFT                        208
#define IDC_ROUND                       209
#define IDC_PUSHED                      209
#define IDC_TEXT                        209
#define IDC_CLEARPUSHED                 210
#define IDC_HOVER                       211
#define IDC_EXPRESSION                  211
#define IDC_DISABLED                    212
#define IDC_VARTYPE                     212
#define IDC_CLEARDISABLED               213
#define IDC_EVALUATE_SOURCE             216
#define IDC_VALUE                       218
#define IDC_DESC                        219
#define IDC_NAME                        220
#define IDC_INTERVAL                    220
#define IDC_ENABLED                     221
#define IDC_LIST                        222
#define IDC_SEPARATOR                   224
#define IDC_CHECK                       225
#define IDC_DISABLE                     226
#define IDC_INSERT                      227
#define IDC_REMOVE                      228
#define IDC_UP                          229
#define IDC_DOWN                        230
#define IDC_BUTTON_DISPLAYED            231
#define IDC_FILLTYPE                    232
#define IDC_BUTTON_CAPTION              232
#define IDC_LEFT                        233
#define IDC_HORFILLDIR                  234
#define IDC_RIGHT                       234
#define IDC_VERFILLDIR                  235
#define IDC_EDGETYPE                    236
#define IDC_TREE                        236
#define IDC_TEXTFONT_PICK               238
#define IDC_ACCEL_KEY                   238
#define IDC_FILLCOLOR                   239
#define IDC_ACCEL_KEY_ENABLE            239
#define IDC_HIGHLIGHT_EDGECOLOR         240
#define IDC_TEXT_FONT                   240
#define IDC_EDGECOLOR                   241
#define IDC_HIGHLIGHT_FILLCOLOR         242
#define IDC_EDGEWIDTHSPIN               246
#define IDC_HORFILLSPIN                 247
#define IDC_VERFILLSPIN                 248

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         240
#define _APS_NEXT_SYMED_VALUE           172
#endif
#endif
